FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*-jar-with-dependencies.jar app.jar
RUN unzip -l app.jar | grep HereToSlay
ENTRYPOINT ["java", "-cp", "app.jar", "org.br.heretoslay.HereToSlay"]