package org.br.heretoslay.entity;

public enum MatchState {
    ORDER_SELECTION,
    PARTY_LEADER_SELECTION,
    GAMEPLAY,
    WAITING_HERO_ROLL,
    WAITING_MONSTER_ROLL,
    SELECTING_CARDS,
    SELECTING_HAND_CARDS,
    APPLYING_CARD_EFFECTS,
    APPLYING_MODIFIER,
    SELECTING_PLAYER,
    CHALLENGE_WINDOW,
    CHALLENGE_ROLL,
    FINISHED
}
