events {
    worker_connections 1024;
}

http {
    upstream websocket_gateways {
        least_conn;
        server gateway:8887;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://websocket_gateways;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            # Mantém a conexão viva por mais tempo
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}